### PR TITLE
Sync TargetFrameworks with Camille

### PR DESCRIPTION
**Pull request by mikaeldui**
❔ Left netstandard1.0.

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
Curious, were there any specific issues that this is fixing?

**Comment by mikaeldui** [comment]
Bumping netcoreapp from 1.0 to 3.1.

But the other...

> .NET 5 and all future versions will always support .NET Standard 2.1 and earlier. The only reason to retarget from .NET Standard to .NET 5 is to gain access to more runtime features, language features, or APIs. So, you can think of .NET 5 as .NET Standard vNext.

> * Use netstandard2.0 to share code between .NET Framework and all other platforms.
> * Use netstandard2.1 to share code between Mono, Xamarin, and .NET Core 3.x.
> * Use net5.0 for code sharing moving forward.

Source: [The future of .NET Standard](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/)

Maybe `net45;net461;netstandard2.0;netstandard2.1;net5.0;net6.0` is better?

[`Newtonsoft.Json`](https://www.nuget.org/packages/Newtonsoft.Json/13.0.1#dependencies-tab) doesn't extend beyond `netstandard2.0`.

**Comment by MingweiSamuel** [comment]
> Maybe `net45;net461;netstandard2.0;netstandard2.1;net5.0;net6.0` is better?
> 
> [`Newtonsoft.Json`](https://www.nuget.org/packages/Newtonsoft.Json/13.0.1) doesn't extend beyond `netstandard2.0`.

Yeah, that looks reasonable, thanks!

**Comment by mikaeldui** [comment]
> .NETCoreApp 1.0
> Microsoft.NETCore.App (>= 1.0.5)
> .NETFramework 4.5
> No dependencies.
> .NETStandard 1.0
> NETStandard.Library (>= 1.6.1)

The [.NET Standard 1.0](https://www.nuget.org/packages/MingweiSamuel.TokenBucket/1.0.1#dependencies-tab) has the `NETStandard.Library` dependency. So it does solve something I guess.

**Comment by mikaeldui** [comment]
@MingweiSamuel maybe `netstandard2.1;net5.0;net6.0` isn't needed? `Newtornsoft.Json` doesn't need it. Then just `net45;net461;netstandard2.0` or `net45;net461;netstandard1.0;netstandard2.0`?

**Pull request merged**
